// app/layout.tsx
import "./globals.css"
import Sidebar from '@/components/nav/sidebar'
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" className="h-full">
      <body className="h-full flex">
        <Sidebar/>
        <main className="flex-1 p-6">
          {children}
        </main>
      </body>
    </html>
  )
}